[alias]
b = "lbuild"
c = "lcheck"
t = "ltest"
r = "lrun"
w = "watch -x lcheck"
wr = "watch -x lrun"
rl = "lrun --example lab"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[expand]
theme = "Solarized (light)"
